<a href="https://colab.research.google.com/github/YuminPark78/PytorchPractice/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
# Lists
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
# Numpy arrays
np1 = np.random.rand(3, 4)
np1

array([[0.50129541, 0.00322109, 0.29366787, 0.70329155],
       [0.08791237, 0.87386922, 0.66926994, 0.27379901],
       [0.92485063, 0.45870418, 0.44086556, 0.61167238]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
# Tensors
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.9853, -0.2751,  1.3810,  1.3918],
        [-0.6193, -0.3608, -0.0472,  0.6403],
        [-1.5984, -1.1592, -0.4246, -0.2069]])

In [ ]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# numpy array -> tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5013, 0.0032, 0.2937, 0.7033],
        [0.0879, 0.8739, 0.6693, 0.2738],
        [0.9249, 0.4587, 0.4409, 0.6117]], dtype=torch.float64)

Tensors are in float32 by default, a change of numpy array to tensor results in float64